'use client';
import {useMemo,useState} from 'react';
import data from '../data/dashboard-data.json';

type V={name:string,block:string,baseline:number,weight:number,sign:1|-1,status:string,methodClass:string,note:string};
const vars=data.hsi.variables as V[];
const registry=data.registry.map(r=>[r.feature,r.domain,r.class,r.status,r.evidence]);
const forecasts=data.experiments.map(r=>[r.horizon,r.marketRF,r.marketEventRF,r.scope]);
const calc=(x:number[])=>Math.max(0,Math.min(100,data.hsi.neutralReference+vars.reduce((s,v,i)=>s+(x[i]-data.hsi.neutralReference)*v.weight*v.sign,0)));
export default function Page(){
 const base=vars.map(v=>v.baseline); const [sc,setSc]=useState(base); const [tab,setTab]=useState<'overview'|'scenario'|'registry'>('overview');
 const b=useMemo(()=>calc(base),[]), s=useMemo(()=>calc(sc),[sc]), d=s-b; const interp=s<25?'Low stress':s<50?'Moderate-low stress':s<75?'Moderate-high stress':'Extreme stress';
 return <main><header><div><p className="eyebrow">HORMUZ ANALYTICS · THESIS DASHBOARD</p><h1>HESI / HSI Decision Dashboard</h1><p>Observed stress · scenario analysis · predictive governance · multi-horizon ML</p></div><div className="version">{data.meta.version}</div></header>
 <nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='scenario'?'active':''} onClick={()=>setTab('scenario')}>HSI Scenario Lab</button><button className={tab==='registry'?'active':''} onClick={()=>setTab('registry')}>Feature Registry</button></nav>
 {tab==='overview'&&<><section className="kpis"><article><span>HESI Effective</span><strong>{data.hesi.effective.toFixed(2)}</strong><small>Last reproducible weekly checkpoint · {data.hesi.asOf}</small></article><article><span>Physical Stress</span><strong>{data.hesi.physical.toFixed(2)}</strong><small>{data.hesi.physicalNote}</small></article><article><span>Market Stress</span><strong>{data.hesi.market.toFixed(2)}</strong><small>{data.hesi.marketNote}</small></article><article><span>HSI Baseline</span><strong>{b.toFixed(2)}</strong><small>Interactive scenario reference</small></article></section>
 <div className="notice"><b>Two-layer architecture.</b> HESI is observed/data-derived stress; HSI is a hypothetical scenario index. Neither is a causal Brent-price elasticity estimate.</div>
 <section className="grid overview"><div className="panel"><h2>ML forecast evidence</h2><p className="sub">Current dashboard reports validated experiment metrics rather than inventing a live price forecast. RMSE values below are from the 2026 daily pilot.</p><div className="forecastHead"><span>Horizon</span><span>Market RF</span><span>Market+Event RF</span><span>Scope</span></div>{forecasts.map(r=><div className="forecast" key={r[0]}>{r.map((x,i)=><b key={i}>{x}</b>)}</div>)}<p className="foot">+3d is a 3-observation proxy in the EIA daily series. A live forecast panel will be activated only when the reproducible data refresh pipeline is connected.</p></div>
 <aside className="panel"><h2>Model governance</h2><div className="class core"><b>Predictive Core</b><span>Market return / momentum / volatility features with OOS support.</span></div><div className="class econ"><b>Economic / Scenario</b><span>Physical, buffer, route, exposure and diagnostic variables without robust incremental OOS admission.</span></div><div className="class excl"><b>Excluded / Robustness</b><span>TOCI negative robustness; Polymarket external benchmark only.</span></div><p className="foot">Economic relevance ≠ incremental predictive relevance.</p></aside></section></>}
 {tab==='scenario'&&<><section className="kpis"><article><span>Baseline HSI</span><strong>{b.toFixed(2)}</strong></article><article><span>Scenario HSI</span><strong>{s.toFixed(2)}</strong></article><article><span>Δ HSI</span><strong>{d>=0?'+':''}{d.toFixed(2)}</strong></article><article><span>Regime</span><strong className="regime">{interp}</strong></article></section><div className="notice"><b>Scenario ≠ causal forecast.</b> Slider changes are not translated into Brent dollars unless an empirical mapping is validated.</div><section className="grid"><div className="panel"><div className="panelTitle"><h2>Scenario controls</h2><button className="reset" onClick={()=>setSc(base)}>Reset baseline</button></div>{vars.map((v,i)=><div className="row" key={v.name}><div className="meta"><div><b>{v.name}</b><small>{v.block} · Economic / Scenario</small></div><span className={'tag '+v.status.toLowerCase()}>{v.status}</span></div><div className="control"><span>{v.baseline}</span><input aria-label={v.name} type="range" min="0" max="100" value={sc[i]} onChange={e=>{const n=[...sc];n[i]=+e.target.value;setSc(n)}}/><output>{sc[i]}</output></div><small>{v.note} · weight {(v.weight*100).toFixed(0)}% · {v.sign>0?'stress ↑':'buffer ↓'}</small></div>)}</div><aside className="panel sticky"><h2>Scenario decomposition</h2>{vars.map((v,i)=>{const c=(sc[i]-base[i])*v.weight*v.sign;return <div className="impact" key={v.name}><span>{v.name}</span><b>{c>=0?'+':''}{c.toFixed(2)}</b></div>})}<hr/><div className="impact total"><span>Net ΔHSI</span><b>{d>=0?'+':''}{d.toFixed(2)}</b></div></aside></section></>}
 {tab==='registry'&&<section className="panel registry"><h2>Master Feature Registry</h2><p className="sub">Web feed of the methodological classification used by the thesis. Data status and methodological class remain separate.</p><div className="table"><div className="tr th"><span>Feature / block</span><span>Domain</span><span>Class</span><span>Status</span><span>Evidence / decision</span></div>{registry.map((r,i)=><div className="tr" key={i}>{r.map((x,j)=><span key={j} className={j===2?x.startsWith('Predictive')?'txtcore':x.startsWith('Economic')?'txtecon':'txtexcl':''}>{x}</span>)}</div>)}</div><div className="notice"><b>Promotion rule:</b> anti-leakage → chronological/purged walk-forward → ablation → common-sample OOS comparison. Classification changes only with new empirical evidence.</div></section>}
 <footer>Source of truth: {data.meta.registry} · {data.meta.hsi} · {data.meta.version} · structured data layer</footer></main>}
